-- seed.sql — applied after migrations on `supabase db reset` (local dev).
-- Phase 1 has nothing to seed: profiles are created by sign-up + the
-- handle_new_user trigger, and the first admin is granted manually
-- (see PHASE1_SETUP.md §4).
--
-- Phase 2 adds the current season here, e.g.:
--   insert into seasons (year, name) values (2026, '2026 Season')
--     on conflict (year) do nothing;
-- Phase 6 seeds the league-wide chat channel.
