-- seed.sql — applied after migrations on `supabase db reset` (local dev).
-- Phase 1 has nothing to seed: profiles are created by sign-up + the
-- handle_new_user trigger, and the first admin is granted manually
-- (see PHASE1_SETUP.md §4).
--
-- Phase 2 seeds the 2026 season inside migration 0003_seasons.sql (idempotent,
-- so it also lands on the hosted project via `supabase db push`).
-- Phase 6 seeds the league-wide chat channel.
